### ISSUE TITLE
Static website:  Implement JS drivers for multistate control

### ISSUE THREAD

**Issue by ajvincent** [ajvincent/es-membrane#100]
- Multistate button must have a constant width, approximately the widest of its child spans
- Button's value property should match the data-state attribute of the first span
- FIrst span should be the only visible one:  rotate states by appending the first span as the last span
- A click causes a state rotation when the button is not disabled.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset will be helpful.

**Comment by ajvincent** [comment]
Blocks #90.

**Comment by ajvincent** [comment]
Evan, you have a right to be angry at me for this, but I'm "moving the goalpost" a little, by adding an extra requirement before this ticket can be resolved.

Specifically, I've just added a test page for anything GUI-related at docs/gui/tests/index.xhtml.  The idea is that any working code should have tests, and that's going to include your multistate button work.

I will not require it as part of the initial pull request for this ticket.  On the plus side, you can use the test page to write your own multistate control and test it there.

**Comment by qk8333** [comment]
I'm down for the challenge. Bring it on.
-------- Original message --------From: "Alexander J. Vincent" <notifications@github.com> Date: 9/26/17  11:08 PM  (GMT-08:00) To: ajvincent/es7-membrane <es7-membrane@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [ajvincent/es7-membrane] Static website: Implement JS drivers for multistate control (#100) 
Evan, you have a right to be angry at me for this, but I'm "moving the goalpost" a little, by adding an extra requirement before this ticket can be resolved.
Specifically, I've just added a test page for anything GUI-related at docs/gui/tests/index.xhtml.  The idea is that any working code should have tests, and that's going to include your multistate button work.
I will not require it as part of the initial pull request for this ticket.  On the plus side, you can use the test page to write your own multistate control and test it there.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ajvincent/es7-membrane","title":"ajvincent/es7-membrane","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ajvincent/es7-membrane"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ajvincent in #100: Evan, you have a right to be angry at me for this, but I'm \"moving the goalpost\" a little, by adding an extra requirement before this ticket can be resolved.\r\n\r\nSpecifically, I've just added a test page for anything GUI-related at docs/gui/tests/index.xhtml.  The idea is that any working code should have tests, and that's going to include your multistate button work.\r\n\r\nI will not require it as part of the initial pull request for this ticket.  On the plus side, you can use the test page to write your own multistate control and test it there."}],"action":{"name":"View Issue","url":"https://github.com/ajvincent/es7-membrane/issues/100#issuecomment-332418870"}}}

**Comment by ajvincent** [comment]
Leaving open for adding multistate to docs/gui/tests/index.html.

**Comment by qk8333** [comment]
It might be a wise idea to initialize the multistate class's value to be the firstElementChild.dataset.state value (in the main html) before the user has to click on the button. Before the "click" event, the value for the class is "undefined". Or, whatever function you implement to call on the value must also be able to call an undefined (as the value "false"). Jasmine testing for these functions will be difficult for me as they edit the DOM and isn't purely JavaScript. If left to my own devices, it will take me a while to figure out how to do that. Any links, advice, and/or references would be very appreciated.

**Comment by ajvincent** [comment]
Evan, see https://github.com/ajvincent/es7-membrane/commit/1fc51f7ec37960a8dfbadc17c80437496a444458 :-)

The way I did it isn't ideal, but it works.

**Comment by ajvincent** [comment]
I'm going to close this out.  While the multistate control was a good idea, ultimately it can't compete with a simple HTML select element for accessibility, or (in the case of more than three states) quick response.
